---
id: Routes
name: Routes
full: URL routing/mapping library
description: >
  Classes for mapping URLs into the controllers and actions of an MVC system. It
  is a port of a Python library, Routes, by Ben Bangert
  (http://routes.groovie.org).
list: dev
type: library
